[package]
name = "committee-iso"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1"
serde = { version = "1", features = ["derive"] }
lazy_static = "1.5.0"
itertools = "0.13.0"
num-bigint = "0.4.6"
hex = "0.4.3"
ark-bn254 = "0.4.0"
ark-ff = "0.4.0"
ssz_rs = { git = "https://github.com/ralexstokes/ssz-rs", rev = "5f1ec833718efa07bbbff427ab28a1eeaa706164" }
sha2 = "0.10.8"
