[package]
name = "step-iso"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1"
serde = { version = "1", features = ["derive"] }
bls12_381 = "0.8.0"
itertools = "0.13.0"
committee-iso = { path = "../iso-committee" }
ssz_rs = { git = "https://github.com/ralexstokes/ssz-rs", rev = "5f1ec833718efa07bbbff427ab28a1eeaa706164" }

sha2 = "0.10.8"
blst = { version = "0.3.13", optional = true }
#sha2_risc0 = { package = "sha2", git = "https://github.com/jonas089/risc0-precompiles", optional = true }


[features]
blst = ["dep:blst"]
