[package]
name = "step-iso"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1"
serde = { version = "1", features = ["derive"] }
ethereum-consensus-types = { git = "https://github.com/ChainSafe/ethereum-consensus-types", branch = "capella", features = [
    "serde",
] }
bls12_381 = "0.8.0"
itertools = "0.13.0"
committee-iso = { path = "../iso-committee" }
