[package]
name = "rz_step"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "=1.1.2", default-features = true, features = ['std'] }
committee-iso = { path = "../../../../iso-committee", features = ["risc0"] }
step-iso = { path = "../../../../iso-step", features = ["risc0"] }
bincode = "1.3.3"
