[package]
name = "rz_committee"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.0.1", default-features = false, features = ['std'] }
committee-iso = { path = "../../../../committee-iso" }
