[package]
name = "rz_committee"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "=1.1.2", default-features = false, features = [
    'std',
] }
committee-iso = { path = "../../../../iso-committee" }
bincode = "1.3.3"

[patch.crates-io]
risc0-zkvm = { git = "https://github.com/risc0/risc0", rev = "79de616506543634cb5d75b9db7f3aee3640d68c" }
risc0-core = { git = "https://github.com/risc0/risc0", rev = "79de616506543634cb5d75b9db7f3aee3640d68c" }
risc0-zkvm-platform = { git = "https://github.com/risc0/risc0", rev = "79de616506543634cb5d75b9db7f3aee3640d68c" }
risc0-zkp = { git = "https://github.com/risc0/risc0", rev = "79de616506543634cb5d75b9db7f3aee3640d68c" }
risc0-binfmt = { git = "https://github.com/risc0/risc0", rev = "79de616506543634cb5d75b9db7f3aee3640d68c" }
risc0-circuit-rv32im = { git = "https://github.com/risc0/risc0", rev = "79de616506543634cb5d75b9db7f3aee3640d68c" }
risc0-circuit-recursion = { git = "https://github.com/risc0/risc0", rev = "79de616506543634cb5d75b9db7f3aee3640d68c" }
risc0-groth16 = { git = "https://github.com/risc0/risc0", rev = "79de616506543634cb5d75b9db7f3aee3640d68c" }
risc0-build = { git = "https://github.com/risc0/risc0", rev = "79de616506543634cb5d75b9db7f3aee3640d68c" }
